routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Fungsi  Route::resource di isinya ialah dimana Get,Post,delete,put jadi satu itu yang dinamakan resource
Route::resource('mahasiswacrud','MahasiswaCRUDController'); 

app/Mahasiswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    //untuk mengisi nama tabel
    protected $table = 'mahasiswa';
    // untuk mengisi nama field dalam tabel
    public $fillable = ['nama', 'alamat', 'jurusan'];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Contact\ContactCreateRequest;
use App\Http\Requests\Contact\ContactEditRequest;
use Illuminate\Http\Request;
use App\Domain\Contracts\ContactInterface;

class ContactController extends Controller
{

    /**
     * @var ContactInterface
     */
    protected $contact;

    /**
     * ContactController constructor.
     * @param ContactInterface $contact
     */
    public function __construct(ContactInterface $contact)
    {
        $this->contact = $contact;
    }

    /**
     * @api {get} api/contacts Request Contact with Paginate
     * @apiName GetContactWithPaginate
     * @apiGroup Contact
     *
     * @apiParam {Number} page Paginate contact lists
     */
    public function index(Request $request)
    {
        return $this->contact->paginate(10, $request->input('page'), $column = ['*'], '', $request->input('search'));
    }

    /**
     * @api {get} api/contacts/id Request Get Contact
     * @apiName GetContact
     * @apiGroup Contact
     *
     * @apiParam {Number} id id_contact
     * @apiSuccess {Number} id id_contact
     * @apiSuccess {Varchar} name name of contact
     * @apiSuccess {Varchar} address name of address
     * @apiSuccess {Varchar} email email of contact
     * @apiSuccess {Number} phone phone of contact
     */
    public function show($id)
    {
        return $this->contact->findById($id);
    }

    /**
     * @api {post} api/contacts/ Request Post Contact
     * @apiName PostContact
     * @apiGroup Contact
     *
     *
     * @apiParam {Varchar} name name of contact
     * @apiParam {Varchar} email email of contact
     * @apiParam {Varchar} address email of address
     * @apiParam {Float} phone phone of contact
     * @apiSuccess {Number} id id of contact
     */
    public function store(ContactCreateRequest $request)
    {
        return $this->contact->create($request->all());
    }

    /**
     * @api {put} api/contacts/id Request Update Contact by ID
     * @apiName UpdateContactByID
     * @apiGroup Contact
     *
     *
     * @apiParam {Varchar} name name of contact
     * @apiParam {Varchar} email email of contact
     * @apiParam {Varchar} address address of contact
     * @apiParam {Float} phone phone of contact
     *
     *
     * @apiError EmailHasRegitered The Email must diffrerent.
     */
    public function update(ContactEditRequest $request, $id)
    {
        return $this->contact->update($id, $request->all());
    }

    /**
     * @api {delete} api/contacts/id Request Delete Contact by ID
     * @apiName DeleteContactByID
     * @apiGroup Contact
     *
     * @apiParam {Number} id id of contact
     *
     *
     * @apiError ContactNotFound The <code>id</code> of the Contact was not found.
     * @apiError NoAccessRight Only authenticated Admins can access the data.
     */
    public function destroy($id)
    {
        return $this->contact->delete($id);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/KendaraarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class KendaraarController extends Controller
{
    //
}

app/Http/Controllers/MahasiswaCRUDController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mahasiswa;
use App\Http\Requests;

class MahasiswaCRUDController extends Controller
{
        public function index(Request $request)
    {
        $mahasiswa = Mahasiswa::orderBy('id', 'DESC')->paginate(5);
        //compact digunakan untuk mentransfer data ke resources/views

        //view digunakan untuk menghubungkan ke tampilan pada resources/views
        return view('mahasiswa.index', compact('mahasiswa'))
              ->with('i', ($request->input('page', 1) - 1) * 5);

    }

    public function create(){
        //view digunakan untuk menghubungkan ke tampilan pada resources/views
        return view('mahasiswa.create');

    }

    public function store(Request $request)
    {
        //validate untuk memvalidasi suatu field yang akan di gunakan untuk create atau update
        $this->validate($request, [
            'nama'    => 'required',
            'alamat'  => 'required',
            'jurusan' => 'required',
        ]);

        Mahasiswa::create($request->all());
        //route digunakan untuk menghubungkan ke folder routes/web
        return redirect()->route('mahasiswacrud.index')
              ->with('success', 'mahasiswa created successfully');
    }

    public function show($id)
    {
        $mahasiswa = Mahasiswa::find($id);
        //view digunakan untuk menghubungkan ke tampilan pada resources/views
        return view('mahasiswa.show', compact('mahasiswa'));
    }

    public function edit($id)
    {
        //Fungsi find digunakan untuk mencari data berdasarkan id atau lainnya

        $mahasiswa = Mahasiswa::find($id);
        //compact digunakan untuk mentransfer data ke resources/views
        //view digunakan untuk menghubungkan ke tampilan pada resources/views

        return view('mahasiswa.edit', compact('mahasiswa'));
    }

        public function update(Request $request, $id)
    {
        //validate untuk memvalidasi suatu field yang akan di gunakan untuk create atau update

        $this->validate($request, [
            'nama'    => 'required',
            'alamat'  => 'required',
            'jurusan' => 'required',
            ]);
        //Fungsi find digunakan untuk mencari data berdasarkan id atau lainnya

        Mahasiswa::find($id)->update($request->all());
        //route digunakan untuk menghubungkan ke folder routes/web

        return redirect()->route('mahasiswacrud.index')
            ->with('success', 'mahasiswa updated successfully');
    }

        public function destroy($id)
    {
        //Fungsi find digunakan untuk mencari data berdasarkan id atau lainnya
        Mahasiswa::find($id)->delete();
        //route digunakan untuk menghubungkan ke folder routes/web

        return redirect()->route('mahasiswacrud.index')
            ->with('success', 'mahasiswa deleted successfully');
    }







}

resources/views/mahasiswa/create.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Tambah  Mahasiswa</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('mahasiswacrud.index') }}"> Back</a>
            </div>
        </div>
    </div>
    {{--$errors Untuk menampilkan Validasi ketika ada yang error--}}
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(array('route' => 'mahasiswacrud.store','method'=>'POST')) !!}
    @include('mahasiswa.Form')
    {!! Form::close() !!}
@endsection

resources/views/mahasiswa/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Mahasiswa</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('mahasiswacrud.index') }}"> Back</a>
            </div>
        </div>
    </div>
    {{--$errors Untuk menampilkan Validasi ketika ada yang error--}}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::model($mahasiswa, ['method' => 'PATCH','route' => ['mahasiswacrud.update', $mahasiswa->id]]) !!}
    @include('mahasiswa.Form')
    {!! Form::close() !!}
@endsection

resources/views/mahasiswa/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nama:</strong>
            {!! Form::text('nama', null, array('placeholder' => 'Nama','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Alamat:</strong>
            {!! Form::text('alamat', null, array('placeholder' => 'Alamat','class' => 'form-control')) !!}

        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Jurusan:</strong>
            {!! Form::text('jurusan', null, array('placeholder' => 'Jurusan','class' => 'form-control')) !!}

        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
@endsection

resources/views/mahasiswa/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Mahasiswa CRUD</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('mahasiswacrud.create') }}"> Create Mahasiswa</a>
                {{--href="{{ route('mahasiswacrud.create') }}" file ini di dapat dari folder routes/web.php yang ada didalam route::resource--}}
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    {{--// $message untuk menampilkan pesan dari BelajarCRUDController.php yang terdiri dari pesan berhasil maupun error--}}
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Alamat</th>
            <th>Jurusan</th>
            <th width="280px">Action</th>
        </tr>

        @foreach ($mahasiswa as $field)
            {{--$mahasiswa di ambil dari BelajarCRUDController.php yang berasal dari function index dan di dapat dari fungsi compact('mahasiswa')--}}
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $field->nama}}</td>
                <td>{{ $field->alamat}}</td>
                <td>{{ $field->jurusan}}</td>
                <td>
                    <a class="btn btn-info" href="{{ route('mahasiswacrud.show',$field->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('mahasiswacrud.edit',$field->id) }}">Edit</a>
                    {!! Form::open(['method' => 'DELETE','route' => ['mahasiswacrud.destroy', $field->id],'style'=>'display:inline']) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
    </table>
    {!! $mahasiswa->render() !!}
@endsection

resources/views/mahasiswa/show.blade.php
@extends('layouts.default')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('mahasiswacrud.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{--$mahasiswa di ambil dari BelajarCRUDController.php yang berasal dari function show dan di dapat dari fungsi compact('mahasiswa')--}}
                {{ $mahasiswa->nama}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Alamat:</strong>
                {{--$mahasiswa di ambil dari BelajarCRUDController.php yang berasal dari function show dan di dapat dari fungsi compact('mahasiswa')--}}
                {{ $mahasiswa->alamat}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Jurusan:</strong>
                {{--$mahasiswa di ambil dari BelajarCRUDController.php yang berasal dari function show dan di dapat dari fungsi compact('mahasiswa')--}}
                {{ $mahasiswa->jurusan}}
            </div>
        </div>
    </div>
@endsection